### ISSUE TITLE
SWTbahn Standard layout mistake?

### ISSUE THREAD

**Issue by eyip002** [uniba-swt/swtbahn-cli#13]
The track layout for SWTbahn Standard as defined in the config.bahn with an anti-clockwise reading. This means that point1.straight should be connected to buffer3.up, rather than the following:
https://github.com/uniba-swt/swtbahn-cli/blob/aee7b3cf99adc8e6820fb031022c19498bcbf295/configurations/swtbahn-standard/config.bahn#L164

**Comment by trinnguyen** [comment]
Hi @eyip002 @tmh2211, I confirm that this is a mistake on Standard layout. I fixed it and sent a pull request here: https://github.com/uniba-swt/swtbahn-cli/pull/14. Since this is a buffer block with no signal on it, there is no change on the generated configuration files.
