### ISSUE TITLE
Inconsistent assignment of values for platformlights in YAML configuration file

### ISSUE THREAD

**Issue by eyip002** [uniba-swt/swtbahn-cli#2]
In `configurations/swtbahn-standard/bidib_track_config.yml`, the assignment of values to platformlights' `on`/`off` ids are inconsistent to those used for the `sync` and `lanterns`.

Change the values for `on`/`off` below ...
https://github.com/uniba-swt/swtbahn-cli/blob/7a858714066aabaa021a19c518b70ef570fc2a44/configurations/swtbahn-standard/bidib_track_config.yml#L227-L234
... to be consistent with ...
https://github.com/uniba-swt/swtbahn-cli/blob/7a858714066aabaa021a19c518b70ef570fc2a44/configurations/swtbahn-standard/bidib_track_config.yml#L116-L131

**Comment by clehanka** [comment]
I switched the macro so it is now consistent, see commit 9215b3d
