### ISSUE TITLE
File upload after startup fails after file upload without startup

### ISSUE THREAD

**Issue by hosakb** [uniba-swt/swtbahn-cli#29]
File Upload failed after pressing file upload before startup, followed by a file upload after pressing the Startup button.

The Bug occured after the following inpuit combination.
Upload (Engine train_engine_eugene.sctx could not be compiled or loaded!) -> Startup (OK) -> Upload (Engine train_engine_eugene.sctx could not be compiled or loaded!) -> Startup (System already running!)

This bug could not be reproduced.

**Comment by eyip002** [comment]
Still cannot reproduce
