### ISSUE TITLE
Route sometimes not released after driving with automatic interlocking has finished 

### ISSUE THREAD

**Issue by BLuedtke** [uniba-swt/swtbahn-cli#47]
Driving with automatic interlocking -> after route has finished (client: drive_route), the route should be released.

Sometimes, the route is not released. 
In such a case, where the route wasnt released, a subsequent shutdown command did not complete and blocked indefinitely.

**Comment by eyip002** [comment]
Route granted was from signal 7 to signal 2

**Comment by eyip002** [comment]
Can no longer replicate bug after fixing #46
